### ISSUE TITLE
[Config] Persistent creative paintings

### ISSUE THREAD

**Issue by Foreck1** [jbredwards/JSON-Paintings-Mod#2]
Config option to make all `isCreative` paintings drop themselves regardless of whether the player is shifting or not. That way, important paintings will never get lost. If the player wants to access any of the non-creative ones, they can simply craft a default painting.
Could be an additional key on the main JSON file if you want to avoid having a separate file.

**Comment by jbredwards** [comment]
added in v1.3.0, in the form of a new `alwaysCapture` tag. For each `isCreative` painting, this value defaults to true.
